# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.108.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # sh("rm -f ../*.ipa")
    # sh("rm -f ../*.dSYM.*")
    increment_build_number
    gym
    pilot(skip_waiting_for_build_processing: true)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "peeriomobile")
    deliver(force: true)
    # frameit
  end

  after_all do |lane|
    commit_version_bump(message: "chore(project): fastlane version bump")
    push_to_git_remote
    clean_build_artifacts
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

platform :android do
  lane :alpha do
  supply(
    track: "alpha",
    apk_paths: [
    "apk/release-armeabi-v7a-signed.apk",
    "apk/release-x86-signed.apk" ],
    json_key: "gp-service.json",
    package_name: "com.peerio.app",
    skip_upload_metadata: true,
    skip_upload_screenshots: true,
    skip_upload_images: true,
    validate_only: false
  )
  end
end

platform :android do
  lane :beta do
  supply(
    track: "beta",
    apk_paths: [
    "android/app/build/outputs/apk/app-armeabi-v7a-release-signed.apk",
    "android/app/build/outputs/apk/app-x86-release-signed.apk" ],
    json_key: "gp-service.json",
    package_name: "com.peerio.app",
    skip_upload_metadata: true,
    skip_upload_screenshots: true,
    skip_upload_images: true,
    validate_only: false
  )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
